### ISSUE TITLE
Support .any.js tests

### ISSUE THREAD

**Issue by domenic** [domenic/wpt-runner#11]
... and ideally then port the [streams tests](https://github.com/web-platform-tests/wpt/tree/master/streams) to [.any.js format](https://web-platform-tests.org/writing-tests/testharness.html), removing their [custom-generated wrappers](https://github.com/web-platform-tests/wpt/blob/24373750793a107c28dbfde50d61cfae192fb485/streams/generate-test-wrappers.js)

The easiest way to do this is probably to copy the logic from https://github.com/web-platform-tests/wpt/blob/24373750793a107c28dbfde50d61cfae192fb485/tools/serve/serve.py#L219 into this project.

/cc @MattiasBuelens

Forked from https://github.com/nodejs/whatwg-stream/issues/1#issuecomment-436360523

**Comment by MattiasBuelens** [comment]
PR for porting the streams tests: web-platform-tests/wpt#14172
